# /services/pdf_generator.py

from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
import io
import requests

def generate_audit_pdf(claim_id: str, damages_summary: str, audit_result: str) -> bytes:
    """
    Generates a Genesis-branded PDF report for a claim audit.
    """
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter

    # Insert Genesis Logo (Placeholder)
    try:
        logo_url = "https://via.placeholder.com/150x50.png?text=Genesis"
        logo_img = ImageReader(requests.get(logo_url, stream=True).raw)
        c.drawImage(logo_img, 50, height - 80, width=150, height=50)
    except Exception as e:
        print(f"Logo load failed: {e}")

    # Title
    c.setFont("Helvetica-Bold", 18)
    c.drawString(220, height - 50, "Genesis Claim Audit Report")

    # Audit Content
    c.setFont("Helvetica", 12)
    c.drawString(50, height - 140, f"Claim ID: {claim_id}")
    c.drawString(50, height - 160, "Damages Summary:")
    text = c.beginText(50, height - 180)
    text.setFont("Helvetica", 12)
    text.textLines(damages_summary)
    c.drawText(text)

    c.drawString(50, height - 250, "Audit Findings:")
    audit_text = c.beginText(50, height - 270)
    audit_text.setFont("Helvetica", 12)
    audit_text.textLines(audit_result)
    c.drawText(audit_text)

    # Footer Note
    c.setFont("Helvetica-Oblique", 8)
    c.drawString(50, 30, "Generated by Genesis Claim Audit Platform © 2025 PlaintiffMax Pty Ltd")

    c.showPage()
    c.save()

    buffer.seek(0)
    return buffer.getvalue()
